### PR TITLE
Use maven wagon

### PR DESCRIPTION
**Pull request by pascalgn**
Changed the `remote` Mojo to use the Maven Wagon infrastructure to check for the existence of artifacts. That way, settings like proxy and authentication can be applied by specifying a server ID.

Provided a setting to set the property as user property.

Provided a setting to fail the build if an artifact exists (or does not exist), see #1.

### CODE REVIEW

**Comment by chonton** [comment]
I am reviewing now and have some changes.  Could you make sure I can modify your pull request?

**Comment by pascalgn** [comment]
Thanks! "Allow edits from maintainers" is checked, so you should be able to push to this branch.

**Comment by chonton** [comment]
Done with changes.  Please review.  Please test with your environment and let me know whether to release.

**Comment by pascalgn** [comment]
Yes, it still works with my environment. Looks good to me!

**Pull request merged**
